# use java support.
language: java

# run in container.
sudo: false

# use linux as operating system.
os: linux

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
      if: branch = master OR tag =~ ^v1\.[0-9]+\.[0-9]+ # match v1.x.x
    - jdk: openjdk11
      if: branch = jdk10 OR tag =~ ^v2\.[0-9]+\.[0-9]+ # match v2.x.x
    - language: perl
      perl:
        - "5.30"
      before_script:
        - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus < yes
        - sudo cpanm App::cpanminus
        - sudo cpanm MDevel::Autoflush
# configure xvfb screen.
services:
  - xvfb

before_install:
  - sudo apt-get install -y openjfx

# skip install stage.
install: true

# run maven build.
script:
  - mvn test

cache:
  directories:
    - $HOME/.m2

deploy:
  # Deploy snapshots & releases on every commit made to master
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean test -fn"
    skip_cleanup: true
    on:
      all_branches: true