# use java support.
language: java

# run in container.
sudo: false

# use linux as operating system.
os: linux

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
      if: branch = master OR tag =~ ^v1\.[0-9]+\.[0-9]+ # match v1.x.x

# configure xvfb screen.
services:
  - xvfb

before_install:
  - sudo apt-get install -y openjfx
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm App::cpanminus
  - sudo cpanm Devel::Autoflush
# skip install stage.
install: true

## run maven build.
#script:
#  - mvn test

cache:
  directories:
    - $HOME/.m2

before_script:
  "mvn dependency:resolve"

script:
  "mvn clean test"